//
//  DNA.java
//  
//
//  Created by Kashyap Kaul on 4/23/13.
//  Copyright 2013 __MyCompanyName__. All rights reserved.
//

public class DNA {

	String S1;
	String S2;
	String S3;
	int maxscore = 0;
	int[][] M;
	int[][] D;
	static final int diag = 1;
	static final int left = 2;
	static final int up = 3;
	
	public void DNA(String seq1, String seq2)
	{
		S1 ="." + seq1;
		S2 ="." + seq2;
		S3 = "";
		M = new int[S1.length()][S2.length()];
		D = new int[S1.length()][S2.length()];

	}//Constructor
	
	
	
	public int Match(int i, int j)
	{
		if ((S1.charAt(i)) == (S2.charAt(j))){
			return 1;
		}
		else 
			return 0;
	}//Match
	
	
	public int Pen()
	{
		return 0;
	}//Pen
	
	public int max(int a,int b, int c)
	{
		int max = a;
		if (b>a)
		{max = b;}
		if (c>b)
		{max = c;}
		return max;

	}//max
	
	
	public void matrixfill()
	{
		for(int i = 1;i< S1.length(); i++)
		{
			for(int j = 1;j<S2.length(); j++)
			{
				
				int diag = M[i-1][j-1] + Match(i,j);
				int top = M[i][j-1];
				int left = M[i-1][j];
				M[i][j] = max(diag,left,top);
				if (M[i][j] == diag){D[i][j] = 1;}
				if (M[i][j] == left){D[i][j] = 2;}
				if (M[i][j] == top){D[i][j] = 3;}
				if (M[i][j] == 0){D[i][j] = 0;}
			}
		}
				}//matrixfill
	
	public void traceback()
	{
		String t1 = "";
		String t2 = "";
		int x = S1.length()-1;
		int y = S2.length()-1;
		while(x != 0 || y != 0){
			
			if  (D[x][y] == 0){
				t1 = S1.charAt(x)  + t1;
				t2 = S2.charAt(y) + t2;
				S3 = " " + S3;
				maxscore = maxscore + Match(x,y);
				x--;
				y--;
			}
			if (D[x][y] == 1){
				t1 =S1.charAt(x) + t1;
				t2 = S2.charAt(y) + t2;
				S3 = "|" + S3;
				maxscore = maxscore + Match(x,y);
				x--;
				y--;
				
			}
			
			if  (D[x][y] == 2){
				t1 =S1.charAt(x) + t1;
				t2 = "_" + t2;
				S3 =  " " + S3;
				maxscore = maxscore + Pen();
				x--;
			}
			
			if  (D[x][y] == 3){
					t1 = "_" + t1;
					t2 = S2.charAt(y) + t2;
					S3 = " " + S3;
				maxscore = maxscore + Pen();
				y--;
			}
		}
		x--;
		y--;
		S1 = t1;
		S2 = t2;
		
	}//traceback
	
		
	
	public void printseq()
	{
		System.out.println(S1);
		System.out.println(S3);
		System.out.println(S2);
		System.out.println("DNA Match Score = "+ maxscore);
		
	}//printseq
		
	public static void main(String[] args)
    {
		
		//String seq1 = "AATTCGC";
		//String seq2 = "AACGCT";
		
		String seq1 = "AACAGATGAGCGACGAGGCCGCGTCGAAGAATGAGGATCGCTGACCGGATCGTCTGCATACAAGCTCCGAGTTCAGCTTAGGTCCAGGGCCCCGGGTATCCGGGTGCTTTTATTCCCATGAATTGGCAGTATGACACACTATTAATAAACTTCCGCTACTTGTGGAGTTTAGTCGTGTAAGCAGTCAATAGTATATGGTTCGTCAACCGAGCAGATATGGCGACGAGGAATCCATAGTCAGTTGGACTGAATCTCGCAAAAAGTGGCGGACCACGAGGAAGGAAACATGGCCCCCGAATGTCCCGTATAAAGGTAACGCCCCTGGGAACTGATCTCGCTAGCGCGAAATAGAGATGAAAGCGTTTCTTCCACCGAGCTCCTGGATCGGTCATATGGTCACCCGCGCTAGGTTCCACAGAGTGAATTTCGTACCTCCACCCCAAGTGAGATCCGTAAGAGTTGGGTCACGGGATACGGACTACAGTGATGATTTGTAATAAATTATGGGTCCTATGCGGTTATGTCCTTGTGCCCCGTCGTTGCCGCGGACTACCGACAGTATTAAGTAGGCAGCATTGAAACAGCTCGGTCAACTCACCTTACGAAGTTCTGAAAATGCTTCGTGTCGAGTCTCCTAGCGAACGCAATAGGGCCCAGCTATATATAAGAACAATGTTTCCATCATGGGATTCGTGACACGCGATGACAGAGCGAAGTGTTTATGACAAGGATACTCGTTTAAGGTGCACTTGACAGAAACTTTCGCGCTGAGTCCCGAACACGAAATTCAAGTCGAAACACAACCTGATGCGGTGCTACAGAGTTCGTTGTGCATGTGACCAAGAACCGAGTGAACCGCACGAACCTGCCAAGCCGAGCTAGGTGTAAGACAACAAGTACAAAGTAATAGGGGTGCCTACAAATGCGGCAGAGGATTCTTAGCCGGAAATCGCCTCGAGTGTGGAAAACCTTAGCGCCTCATTATAAGTTATGTTTATAAAAAAATTATTTGTAAAACACTGCGAGGGAGGCGCGGAACAGCGTGATGCCCGTCTACGTATCTCCACGTGATGCTAAGAATCTATTCCGCAGTCGCTGGTGGTCCATAGTCTGATAATCATCTAGAGTTTGAAAACGAAGTATAGCCGCGCCACCTCGATTTAGAGTTGGAAATGTCACGCTAACGTTAGGCTTCTGCTACACCCTCGAAAACATATCACACACTCCCTCGGAGGGTCCGCTCGCTGGCAACTGCGCCCATATGACACCGTTGCGACCTAGTACATGGGCGCTCGCATCTGTTGTCGGTTGCCAATCGACAGACACCTGAATCAGAGCCTACATCTGATTGTGTCCATCCCAAGTTCGCCATAACCTCTTCAGAGCCCACCACGTAGTAGGAGTAATTCATTCCACTACCGTATCCTGGGAGGATAGCATGGCGTAACTCAAGCCGCGTACCGAGGTCTCCAGTAGTCATCTTCCGGAATTGAAGTCGGGTAATATGGTTACTGACTGAATTCGACAGTTTCTGAGAGACTCGCTTCCTTGAGCTCACGCAGACGTCAGCCGCCGCCGTACTCGCTCGAGAGACGCTGCTTGTGACCTACCAACCGTGTTTGTTTATGACTAGGTTCCTCGGTAGTCGAGTCCTCTGCGACCTCATATTAAGGACTATAAGGCGTCCTAACCAGCATACTCGTACTTGGCATAGCTCCCATTTTCCCCCCTGGAGGATCGTACGCTGAAGGTAACGACGCAACATCCGTTCTACCGAACAGTGGCAGCCAGAGTGACCAGCAACAGTATTCCTCACGTGTTCATGACCAAATGAGACATGATCGCACCAAAAAGCTCCGTCCAGCTCATGTGTGCTAGCTGTATTGCCTTACACAAGCGCGCTTGAGTGCCTTGGCCAGAGAGTATATACGTGCTCTTCGTAATAGATGGTACATTAGTCGAGTTTTCATACCTACGTAGACACCGGCCGTACCGCCTTT";
		
		//billy
		//String seq2 = "AACAGATGAGCGACGAGGCCCGTCGAGAATGACGATCGCCGACCGATCGTCTACATAAAGATCCGGTTCGCTTAGGTCCAGGGCCCCGTGTATCCGGGTGCTTTTATCCCATGACTGGCAGTATACCACTATTACTAAATTGCGCTACTTGTGGAGTTTGTCTTAAGCAGTCATAGTATGTGCGTCAACCGGAGATATGGCGAAAGGAATCCATTGTCGTGGACTGAATCTCGCAAAAGTGGCGGACACGAGGAAGGAAACATGTCCCCGAATTGCGTATAAAGGTACGCCCCTGGGAACTGATCTCGTAGCGCGAAATCGAGATGAAAGCGTTTCTTCCACAGTCCTGGATCGGTCATAGGTCACCCGCGCTAGTTCCACAGAGTGAATTTGTACCTCCACCCCAAGTGAGATCCGTAAGAGTTGGTACGGGATACGGACTACAGTGATGATTTGTAATAAATTATGGTCTATGGGGTTATGTCCTTGTGCCGTCGTTGCCGCGGACTACCGGAGCTTAAGTAGGCAGCATTGAAACAGCTCGTCAACTCACCTTACGAAGTTCTGAAAATGCTTCTGTCGAGTCTCCTAGCAACGCAATAGGGCCAGCGATATAAGAGAATGTTTCGACCGGGATTCGTGACAAGCATGACAAGCGAAGTGTTATGACGAGGATACTCGTTAAGGTGCGCTTACAGAATCTTTCGCGCGAGTCCCGAACACCAATTCAAGTCCAAACACAACCTGATCGGTGCTACAGAGTTCGTTGTGCATGTGACCAAGAACCAAGTGACCGCACGAACCTGCCAAGCCGAGTAGGTGTAAGACAACAAGTACACAGTAATAGGGGGCACAATTGCGGCAGAGGATTCTTAGCCGGAAATCCCTCATGTGGAAAACCTTAGCGCCTCATTATAAGTTATGTTTAAAAAAATTATTTGTACACACTGCGAGGAGGCGCGGAACAGCGTGTGCCCGTCTACGTATCTCCACGTGATGCTAAGATCTATTCGCAGTCGCTGGTGGTCCATAGTCTGATATCATGAGTTTGAAACGAAGTATAGCCGCGCAACCTCGATTTAGAGTTGGAAAGTCACGCTAAAGTTAGGCTTTGCTACCCCTCGAAAACATACACACACTCCCCGGAGTCCGCTAGCTGCAACTGCGCCATTTGACACCGTGCGACCTAGTACAGGGGGCTCGCATCTGTTGTCGGTTGCAATCGCCGTCACCTCAATCAGACCAACATCTGATTGTCTCGATCCCAAGTTCGCCATAACCTCTTCCGAGCCCACCACTTAGAGGAGTAAATCATTCCACTCCGTATCCTGGGAGGCTCCATGCGTAACTCAAGCCGCGTACCGAGGTCTCCAGGTCATTTCCGGAATTGAAGTCGGGTAATATGGTTACTGACTGAATCGACAGTTTCTGCGAGACCGCTTCCTTGAGCTCACGCAGACGTCAGCGCCGCCTACTCGCTGAGAGACGCTGTTTGTGACCTACCAACCTGTTTGTTTATGATACGTTCTCGCTAGTCAGGCCTCGCGACCTCATATTAAGGACTATAAGGCGTCCTAACCAGCGTACTCGTACTTGGCATAGCCCCATTTTCCCCCTGGAGGATCGTACGCTGAAGGTAGACGCAACATCCGTTTACCGAACAGTGGCAGCCAGAGTGACCAGCAACAGTATTCCTCACGTGTTCATGACCAATGAGACATGATCGCACCAAAAGGCTCCGTCCATTCATGTGTACTAGCTGTATTGCCTTACACAAGCGCACTTGAGTGCCTTGGCTAGAGAGTATATACGTGCTTTCGAATAGATGGTCATTAGTCGAGTTTTCATCCGACGTAGATCCGGCCGACCGCTTTT";
		
		//eric
		//String seq2 = "AAAGATAGCGACGAGGCCGCTCGAAGAATGAGCATCGCTGACAGATCGTCTGCATACAAGCTCCGAGTTCAGCTTAGCAGGGCCCCGGGTATCCGGGTGATTTTATCCCAGATTGGCAGTAGACACACTTTTAATAAACTTCCGCTAATGTGGAGTTAGTCGTGAGCAGTCTTAGTATATGGTTCGTCAACCGAGCAATTGGCGACGAGGAATGCATAGTAGTTGGACTTAATCTCGAAAAAGTGGGGCGACGAGAAGGAAACATGGCTCCGAATGTCCCGTATAAAGTAACGCCCCGGGAACTGATCCGCTAGCGCGAACTAGAGTGAAAGCGTTTCTTCCCCGATCCCCTGGATCGGTCATTGTCACCCGCGCTGTTCCACGAGTGAATTGCGTACCTCACCCCAAGTGAGATCCGAAGAGTTGGGTCACGGGATACGGACTACAGTATGATTTGTAATAAATTATGGGTCCTATGCGTTATGTCCTTGTGCCCCGTCGTTGCCGCGGACTCCGCAGTATTAAGTAGGCAGCATTGAAACAGCTCGGTAAGTCACCCACGAGTTCTGAAAAGCTTCGTGTCGAGTCTCCTAGCGAACGCGATAGGGCCCACAATAGATAAGAACATGTTTCCCTCATGGGATTCGTGACACGCGATGAAAGCGAAGTGTTTTGACAAGGATACTCGTTTAGGTGCACTTGAAAACTTTCGCGTGAGTCCCGAACACGAAATTCCAGTCGAAACCAACTGATGCGGTGCTACAGAGTTCGTTGTGCATGTGACCAAGAACAGGAACCGCACGAACCCCCCAAGCCGAGCTAGGGTAAGTGAACAAGTACAAAGTAAAGGGGTCTAAAATGCGGCATAGGATTCTTAGCCGGATCGCCTGGAGTGTGGAAAACCTTAGCGCTCATTATAAGTTATGTTTATAAAAAAATTATTTAAAAACAATGCGAGGGAGACGCGGAAAGCGTGATGCCCGTCTACGTATCTCCATGTGAGCTAAGAATCTATTCCGCAGTCGCTGGTGGTCCATAGTCTGATAATCATCTAAGTTTGAAAACGAAGTATAGCCGCGCCACCTGATTTAGTTGGAAATGTCACGCTAACGTTAGGCTTCTGCTACACCTGAAAAATATCACACACCCTCGGAGCGTCCGCTCGCTGGCAACTGCGCCCATATGACACGTTGCGACCTAGACATGGGCGCTCTATCTGTTGTCGGGGCCAATCGACAGACACCTGAATCAGAGGCACTCTGATTGTGTCCACCCAAGTCGACATAACCTCTTCAGAGCCCACCACGTAGTAGGAGAAATTCATTCCACTACGTTCCCGGGAGGATAGCATGGGTAACTAGCCCGTACCGAGGTCGCCAGTAGTCATCTTCCGGAATTGAAGTCGGGTAATATGGTTACTGACTGAATTCGACAGTTCAGAGACTCGCTCCCGAGCTCACGCAGACGTCAGCCGCCGACGTACTCGCTCGAAGACGCTCTTGTGACCTCCAACCGTGTTGTCTGACTAGTTTCCTCGTAGTCGAGTCCTCGGCGACTCATATTAAGGACTATAAGGCGTCGAACCAGCACACCGACTTGGCATAGTCTCATTTTCCCCCCTGGAGGATCGTACGCTGAAGTAACGACGCAACAGCCGTTCTACCGAACAGTGGCAGCAGAGTGCCCAGCAACAGTATCTCACGTGTTCATGACCAAATGAGACATGATACACAAAACTCCGCAGCTCATCTGTGCTAGCTTATGCCTTACACAAGCGCGCTTGGTGCTTGGGCAGAGAGTAAACGTGCTCCGTAATAGATGGTACATTAGTCGAGTTTTCATACTACGTAGACACCGGCCGTACCGCCTTC";
		
		//kevin
		String seq2 = "AACAGATGAGCGACGAGGCCGCGTCGAGAAGATGATCGCTGACCGGATCGTCGCATACAAGCTCGAGTTCAGCTTAGGTCCAGGGCCCCGGGTATCCGGGCTTTTATTCCCTGAATTGGCAGTATGACACACTATTAAAAACTTCCGCTACTTGTGGAGTTGTCGTGTAAGCATCAATATATATGGTTCGTCAACCGACAGATATGGCGACGAGTAATCCATAGTCAGTTGGACTGAATTCGCAAAAAGTGGCGGACCAGAGGAGGAAACATGGCCCCTGAATGTCCGTATAGGCACGCCCTGGGAACTGATCTCGCTAGCGCGAATAGAATGAAAGCGTTTCTTCACGAGCTCCTGGATCGGTCATAGGTCACCCGGCCAGGTCCACAAAGTAATTTCGTACCTCCACCCCAAGTGAGAAGCGTAAGAGTTGGCTCACGGGATAGGACACAGTGATGATTTGAATAAATTATGGTCCTATGCGGCTATGCCATGTGCCCCGACGTCCGCGGTACGACAGTATTAAGTAGGCAGCATTGAAACAGCTAGTCAACTCCTTACAAGTTCTGAAATGCTTCGTGTCGAGTCTCCTAGAACGCAACAGGGCCCAGCTGTATATAAGAACAAGGTTTACATCAGGGATTCGTGACACGTGATGAAGTGCGAAGTGTTTATGAAAGATCTCGTTTAGGTGCACTTGACAGAAACTTTCGCGCTGAGTCCCGAACACGAAATTAAGTCGAAACAAACCTGATGCGGTGCAAGAGTTCGTTGTCATGTGACCAAGAACCGAGTGAACCGCACGAACGCCAAGCCGAGCTGGTGTATGACAACAGGTACAAAGTAATATGGGTGCCTATAAATGCGGCAGAGGATTCTTAGCCGGCCATCGCTTGAGGTGGAAAACCTTAGCGCTCTTATAAGTTATGTTTATAAAGAATTTATTGTAAACACTGCGAGGGGGCGCGGAACAGCGTGATGCCCACTCGTATCTCACGTGCTAAGAATCTATTCCGCAGTCGGGTGGTCCATAGTCTGATAATCATCTAGAGTTTGAAACGAAGTACAGCCGTGCCACCTCGATTTAGAGATGAAATGTCACTAACGTTAGCTTCTGCTACACCTCGAAACATATCACACACTCGCTCGGGGGCCGTGCTGGCAACTGCGCCCATATGACACCGTTCGACCTAGTACATGGCCTCGCATCGTTGTCGGTTGCCAATCGACAGACAGCTGAATCAGAGCTACATCTGATGTTCCATCCCAGTTCCCTAACCTCTTAAGAGCCCACCACGTAGTAGGAGTAATTCATTCCACTACCGTATCCTTGGAGATAGCATGGCGTAACTCAAGCCGCGTACCGAGGTCTCCATAGTCTTCTTCCGAATTGAAGTCGGGTATATGGTTACTGACTGAATTCGACAGTTTCTGGAAACTCGCTTCCTTAGCTCACGCAGACGCAGCCGCCGCCGTACTCGCTCGAGGACGCTGCTTGAGACCTACCAACCGTTTTTTTATGACTAGGCTCGGTAGTTAGTCCTCTGCGACTCATATTAAGGACTATGGCGTCCTACAGCATACTCGTACTTGGCATAGCTCCCATTTTCCCCCCTGGAGGATCGACGCTGAAGGTACGACGCAACATCCGTTCTACCAACGGTGGCAGCCAGAGTGACCAGAACAGTATTCCTCACTGTTCACGACCAAAAGAGACATGATCGCACCAAAAATCTCCGTCAGCTCATGTGTGCTAGCTGTATTGCTTACAAAAGCGCGCTGAGTGCCTTGGCGAGAGTATTTAAGTGCTCTTCGTAATAGATGGTACTTAGTCGAGTTTCATACCTACGTAGACACCGGCCTACGGCCTTT";

		//tom
		//String seq2 = "AAAACAGTGCCGATCAAAGTTAACAACCTGACAGCTCTGTTTTATCGGTAGGTGGCTGATTATATCACTCTCCTCGCGCCCTCAGTCTGACGCAAATGCGTCGAACAAATTAAATGCCTGGAGCCGCCTTGGAGCTGGACTACGGTCTAATTGTGTGTCAGGAATGCGAGGCTGTACGCTATATGGAGATCCTTCGGCATAAACTCTAATTGAACTCGTCATACGGATTCGACAACCGAGAAGTCCCGTGCGGAGGTTTACTGCCAGATCCCCGGCCTTTGATCGAGTATCCTCACACGACGAGTTCGTGTCGGCCTTGTTCGGCCGCTGTAATGTTCCTCATTTCAGGCGTACCAAACAACGGGACTGACGGCGTGCCACGGTGTCATGCTATAACCATAATAGCCACGATTCGTCCGACTTAGTAGTTGCTACAGGTCAAGCCTTATCATACTCAAGTATCTCTGCATCACAGAGTTCTCCCCTGGAGCAAAGTTCGGTCCATCGCGGGAGTTTCGATACCTAGCGAGATTCCTCTCGCATTAGGCTAGTCAGCTGATGTAGCTGTTGAAGTCTCTTGTACGAGCGGGGAGCTCCTAGGGGTACGCCGAGGCTGTCCTTGGGGAAGAGCCATGGAGAGTCATCCACAGTGAAGGCGTACGATCGCACCAATGGTGTTTTAGAGGTTATGATGATTGAAGTCTGTCTCTCCTAGCGAACTTTACTTTGCGGGATTTCTGTGTGCTAGGCAAGCACCCAGATAACTGTGGCTGATTACATCTAGGGCCTCAAGGGTCGCAAAATAAGTCCTAACAGACCTTCTTCCGCTGGGACGGACCGGGCAGTTAAGCATGAAGCCCACTGCCATCTGGTACCTCTTTAGACAGCCGATTGGCTGCGCCGCGCCCTCCCGATCATGCCCTGGTCTGCAGGCAATCCGCAGCACATCTGGGCACCTAATACACGCTTTCTATCATTTAAACGAGGTCCCATAGAACGTTGACACCGACGGGTAGCACAAGGATACACAGCGTGCTTTAATGTCATCGTGGAGGTCGATAGGTAGGCTGCCGTGGCCAGGTTCGGGTCGGGCCGTCTTCGTACCCGATTGGCCGATGTACCGTATGGCGAGCAACTGTGTCAAAGGGGACTCGACTACATACCACTCGAGTTTCCGCACCATCGACGGTCACGGCTTGGTGCTACGGAAAAGCCTTAGCGTCTGCACAACTCTGCTGGGAGTACAAAAACCAGTCGCACCGGAAACCAGGTAAACCGCTGTCGCATGCATCTTTAGGCCCCTACCTTGTTGAGTAAATAATCCGGCACTGGTCCTGACTGAATAACCATTAGGCGGCCTAAAGTCTATTCCTACTAATAGGGTGAGTAAATGCGTGTCCATTCCGGGTAAGAAGAGGTGATCCATCCCTGGAACTAAACACCACCTTCTTCACTCTCCCGACAGGTACCCATGAGCACTGACTCGTGCGGAGAGAGCCCCGACCTCTCCTAAGCTTTTGTAGGCTTAAGGTAAGGGAGCGGCCGTTCCAGAGCGGTGCCGACGTAGAGGGACAATCGTCTAACAGGTTAGGAAGATCATTGAAGTGGGTCAAATACCCTCAAGTCTGAAGGCTAAGGTTCAAGGGATCGTCAGTCGCAAAGATGCGAAGTGTGTAGCAGTTCAATATTCTCCGTCTATACAGATCTACCCGTTGGCGACTCCCTTATGCCATAAAACGAAATTAGCCTCGTACGCGCCGCATTGATAAGGGCTGCAAAGGGACCTGAGCACCTCCTTCGTGGTTTCCCTCCCCATTTAGCTGTCTTGCGATAACCTGAGCGCGTTAAAGAGTAAGCGTTACGGTTTACACGTCCTCAGTCCCACAGTGCGTACACCGGGAAGTCATGCGTTTACTGACCAGCAACGACGTACTGTGTTTGTGGCTCAAACATAAGGCGCTAAGGTGCTCGCAAGTTCGGGTCCCGGACTTACAATTTGT";
		//DNA D = new DNA();
		DNA D = new AdvDNA(); 
		D.DNA(seq1,seq2);
		D.matrixfill();
		D.traceback();
		D.printseq();
		
    }
	
	
}


class AdvDNA extends DNA
{
	public int Match(int i, int j)
	{
		if ((S1.charAt(i)) == (S2.charAt(j)))
			return 2;
		else 
			return -1;
	}//Match
	
	
	public int Pen()
	{
		return -1;
	}//Pen
}